# Generated by Django 5.1.3 on 2024-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
